services:
  bridgemanager-op7100br:
    image: bridgemanager:latest
    container_name: BridgeManager-OP7100BR
    environment:
      OP: OP7100BR
    volumes:
      - ${HOME_DIR}/Config:${DOCKER_APP_DIR}/Config
      - ${HOME_DIR}/Logfiles:${DOCKER_APP_DIR}/Logfiles
  bridgemanager-op7200br:
    image: bridgemanager:latest
    container_name: BridgeManager-OP7200BR
    environment:
      OP: OP7200BR
    volumes:
      - ${HOME_DIR}/Config:${DOCKER_APP_DIR}/Config
      - ${HOME_DIR}/Logfiles:${DOCKER_APP_DIR}/Logfiles

