x-volumes:
  config: &config /home/glogware/GLogWare/CompanyCity/Config:/app/Config
  logfiles: &logfiles /home/glogware/GLogWare/CompanyCity/Logfiles:/app/Logfiles

x-tz-env: &tz-env
  TZ: Europe/Zurich

services:
  bridgemanager-op7100br:
    image: bridgemanager:latest
    container_name: BridgeManager-OP7100BR
    environment:
      OP: OP7100BR
      <<: *tz-env
    volumes:
      - *config
      - *logfiles
  bridgemanager-op7200br:
    image: bridgemanager:latest
    container_name: BridgeManager-OP7200BR
    environment:
      OP: OP7200BR
      <<: *tz-env
    volumes:
      - *config
      - *logfiles
  jobmanager:
    image: jobmanager:latest
    container_name: JobManager
    environment:
      <<: *tz-env
    volumes:
      - *config
      - *logfiles
  reserve:
    image: reserve:latest
    container_name: Reserve
    environment:
      <<: *tz-env
    volumes:
      - *config
      - *logfiles
  garbage:
    image: garbage:latest
    container_name: Garbage
    environment:
      <<: *tz-env
    volumes:
      - *config
      - *logfiles
  glogwarewebapp:
     image: glogwarewebapp:latest
     container_name: GLogWareWebApp
     environment:
       <<: *tz-env
     ports:
       - "82:8080"
     volumes:
       - *config
       - *logfiles
