x-volumes:
  config: &config ${HOME_DIR}/Config:${DOCKER_APP_DIR}/Config
  logfiles: &logfiles ${HOME_DIR}/Logfiles:${DOCKER_APP_DIR}/Logfiles

x-tz-env: &tz-env
  TZ: Europe/Zurich

services:
  bridgemanager-op7100br:
    image: bridgemanager:latest
    container_name: BridgeManager-OP7100BR
    environment:
      OP: OP7100BR
      <<: *tz-env
    volumes:
      - *config
      - *logfiles
  bridgemanager-op7200br:
    image: bridgemanager:latest
    container_name: BridgeManager-OP7200BR
    environment:
      OP: OP7200BR
      <<: *tz-env
    volumes:
      - *config
      - *logfiles
