x-volumes:
  config: &config D:/GLogWare2/CompanyCity/Config:/app/Config
  logfiles: &logfiles D:/GLogWare2/CompanyCity/Logfiles:/app/Logfiles

x-tz-env: &tz-env
  TZ: Europe/Zurich

services:
  bridgesimulator-op7100br:
    image: bridgesimulator:latest
    container_name: BridgeSimulator-OP7100BR
    environment:
      OP: OP7100BR
      <<: *tz-env
    ports:
      - "7100:7100"
    volumes:
      - *config
      - *logfiles
  bridgesimulator-op7200br:
    image: bridgesimulator:latest
    container_name: BridgeSimulator-OP7200BR
    environment:
      OP: OP7200BR
      <<: *tz-env
    ports:
      - "7200:7200"
    volumes:
      - *config
      - *logfiles
  simulatorwebapp:
     image: simulatorwebapp:latest
     container_name: SimulatorWebApp
     environment:
       <<: *tz-env
     ports:
       - "81:8080"
     volumes:
       - *config
       - *logfiles