<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Gudel.GLogWare.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Gudel.GLogWare.$(MSBuildProjectName)</RootNamespace>
    <AssemblyTitle>Gudel.GLogWare.$(MSBuildProjectName)</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Tables\Logs\LogPlcCategory.cs" />
    <None Include="Tables\Topology\ResourceModeIdentifiers.cs" />
  </ItemGroup>

</Project>
