<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Gudel.GLogWare.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Gudel.GLogWare.$(MSBuildProjectName)</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Messaging\Plc  Messages\FromPlc\STATConveyor.cs" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    <PackageReference Include="MQTTnet.Extensions.ManagedClient" Version="4.3.7.1207" />
    <PackageReference Include="Novell.Directory.Ldap.NETStandard" Version="4.0.0" />
    <PackageReference Include="Serilog.Enrichers.CallerInfo" Version="1.0.6" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

</Project>
