<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Gudel.GLogWare.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Gudel.GLogWare.$(MSBuildProjectName)</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);SQLSERVER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);SQLSERVER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageReference Include="MQTTnet.Extensions.ManagedClient" Version="4.3.7.1207" />
    <PackageReference Include="Novell.Directory.Ldap.NETStandard" Version="4.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

	<ItemGroup Condition="$(DefineConstants.Contains('SQLSERVER'))">
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
	</ItemGroup>
	<ItemGroup Condition="$(DefineConstants.Contains('ORACLE'))">
		<PackageReference Include="Oracle.EntityFrameworkCore" Version="10.23.26300" />
	</ItemGroup>
	<ItemGroup Condition="$(DefineConstants.Contains('POSTGRES'))">
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
	</ItemGroup>
	<ItemGroup Condition="$(DefineConstants.Contains('MYSQL'))">
		<PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.7" />
	</ItemGroup>
	
</Project>
